### ISSUE TITLE
embyserver_arm64v8 docker image breaking networking on RockPi4b

### ISSUE THREAD

**Issue by Asshall** [MediaBrowser/Emby#3712]
Hiya !

I'm running the `emby/embyserver_arm64v8` docker image (tried `latest` and `4.7.0.15`)  using `docker-compose` on a RockPi4b (distro => ubuntu server, arch => arm64)
And seemingly at random services hosted on the machine will be unreachable but the machine stays pingeable... (I really don't know much about networking)
The only fix I've got is to bring down/up the network interface. Stopping the emby container doesn't fix it either. 
This off course only happens when the emby container is running, I have other containers running in the same machine.

Here is my docker-compose file : 
```yaml
version: "3.7"
services:
  emby:
    image: emby/embyserver_arm64v8
    container_name: embyserver
    environment:
      - UID=1004
      - GID=1003
    volumes:
      - /configs/emby:/config
      - /volume-name:/volume
    ports:
      - 8096:8096
      - 8920:8920
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
```

I can't seem to get relevant emby logs, they are all dated long before the incident... Am I doing something wrong ? 

EDIT :
Well I somehow "fixed" it by putting the emby server behind a reverse proxy...
Accessing it directly will still break everything...
Anybody has any idea of what's going on ? ^^
