### ISSUE TITLE
Go API Client: Invalid Go package name, contains hyphens

### ISSUE THREAD

**Issue by catvec** [MediaBrowser/Emby#3837]
The [auto-generated Go API client](https://github.com/MediaBrowser/Emby.ApiClients/tree/master/Clients/Go) has the `package embyclient-rest-go` in every source file. This is not a valid Go package name. An alternative valid package name would be `embyclient_rest_go` or `embyclient` if we want to follow [best practices for package naming](https://go.dev/blog/package-names)

**Comment by LukePulverenti** [comment]
@softworkz

**Comment by catvec** [comment]
I found a few other issues with the Golang API. It seems like there were some duplicate struct names as well. Here is the [openapi-generator](https://openapi-generator.tech/) config I used to successfully create a compilable version of the Golang API:

```yaml
generatorName: go
inputSpec: # <your emby openapi.json>
outputDir: ./embyclient/
packageName: embyclient

# Required for Golang imports to work
gitHost: github.com
gitUserId: # <your git username>
gitRepoId: # <your git repo>

validateSpec: False
modelNamePrefix: Model

# Go generator
isGoSubmodule: True
withGoMod: False
structPrefix: True
enumClassPrefix: True
```

I then had to run this find and replace on the output files due to a bug where the openapi-generator seems to add the `modelNamePrefix` twice when referring to model structs:

```bash
sed -i 's/ModelModel/Model/g' embyclient/*.go
```
